### ISSUE TITLE
Wrong color (green) for selected item in video, tv show file view

### ISSUE THREAD

**Issue by xhaggi** [vonH/skin.1080xf#1]
In all other windows the color for the selected item is pure white except for the video and tv show window where it is green.

![screenshot000](https://cloud.githubusercontent.com/assets/1878991/5501279/629b906a-8758-11e4-8536-1b6817d421f2.png)

**Comment by vonH** [comment]
"Fixed", although I personally prefer it this way. There may be other instances where this still shows, but after using the File Manager and all viewtypes, only green is displayed when a file is playing.
