### ISSUE TITLE
Added Studio Label to display Studio information in the standard list view

### ISSUE THREAD

**Issue by marank** [vonH/skin.1080xf#10]
In the Youtube Addon, I noticed that channel names are not shown in the standard list view.
So I added/edited the following lines in the file "1080i/ViewTypesVideos.xml":

```
<itemlayout height="100" condition="Container.Content(episodes)">

[...]

                  <control type="label">
                        <description>Year / Genre</description>
                        <posx>362</posx>
                        <posy>43</posy>
                        <width>150</width>  // was: 1028
                        <height>54</height>
                        <font>Font-Condensed-S28</font>
                        <align>left</align>
                        <label>$INFO[ListItem.Premiered]</label>
                        <selectedcolor>D4FFFFFF</selectedcolor>
                        <textcolor>99FFFFFF</textcolor>
                        <scroll>false</scroll>
                    </control>
          // ADDED:
                    <control type="label">
                        <description>Studio</description>
                        <posx>522</posx>
                        <posy>43</posy>
                        <width>700</width>
                        <height>54</height>
                        <font>Font-Condensed-S28</font>
                        <align>left</align>
                        <label>$INFO[ListItem.Studio]</label>
                        <selectedcolor>D4FFFFFF</selectedcolor>
                        <textcolor>99FFFFFF</textcolor>
                        <scroll>false</scroll>
                    </control>
```

I've done the same for the following section, except for changing the _textcolor_ value from "99FFFFFF" to "D4FFFFFF":

```
                 <focusedlayout height="100" condition="Container.Content(episodes)">
```

This way, channel names are displayed next to the date in the standard list view. As a side effect, the Studio is also displayed when viewing episodes of a TV series.
I don't know if this has to be tweaked in any way, this was my first attempt ever to make changes to a skin, but it works for me :)

**Comment by vonH** [comment]
I'm taking a look.

**Comment by vonH** [comment]
I've just tried a few different methods - the List view is simply not designed to show that information. You're best off using another type. Thank you for the suggestion but it's not being added the base version.

**Comment by marank** [comment]
At first I thought that too - but personally, I think that the second line is empty except for the Premiered-Label. I haven't placed it accurately; maybe right-aligned would look better.
I know, maybe I'm the only one who wants this feature, but especially for the Youtube Addon, it's crucial for me, and I want to use the List View since there's enough space to display long video titles. So maybe you could add it as option which is of by default, and turning it on displays the Studio Label somewhere.

**Comment by disrupted** [comment]
@marank I can see why this won't be merged into the base version. you want this feature, others don't, but additional options also mean more clutter users have to deal with.. but maybe I can add it to my [custom fork](https://github.com/freeman212/1080X) of this skin, I'll have a look at it tomorrow. ;-)

**Comment by vonH** [comment]
It can be placed, I added an alternative method of doing it which looked acceptable. The point is that the List view is simply not designed to feature that (I tried it next to the rating, date, title etc) - I wasn't happy with any of them. I may change my mind about it -- or possibly just enable it for YouTube.

**Comment by marank** [comment]
That's a great idea! I searched for a way to enable it just for YouTube earlier, but couldn't find a solution, so I thought it won't be possible. As I said, this is the first time ever I touched any skin files for XBMC/Kodi :)
Thank you for taking your time!
